---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - include_role:
        name: packer_rhel
      when: ansible_os_family|lower == 'redhat'

    # Currently failing.
#    - include_role:
#        name: geerlingguy.packer-debian
#      when: ansible_os_family|lower == 'debian'
